### ISSUE TITLE
null Exception

### ISSUE THREAD

**Issue by Binbiubiubiu** [Coreoz/PPT-Templates#3]
![image](https://user-images.githubusercontent.com/26505011/46659037-af5fae00-cbe6-11e8-90ee-0a36684fd90c.png)

**Comment by Binbiubiubiu** [comment]
paragraph may be   null，hope to fix the bug

**Comment by amanteaux** [comment]
Thank you for your interest in this library!

Do you have an PPT and the sample code to reproduce the issue? Because from the look of it, the nullpointer should occur before. Moreover, do not hesitate to download the library source code in Intellij via Maven to have something better than the decompiled version of the library ;)

**Comment by Binbiubiubiu** [comment]
thank you,I am recode the library source,build a jar to resolve the question

**Comment by amanteaux** [comment]
If you could provide your sample that produce the bug it would be great.
We would then create a fix that everyone that uses the library can benefit.
